# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tourist.Location'),
        ),
    ]
